### ISSUE TITLE
which_posts is not working as intended

### ISSUE THREAD

**Issue by pkoerner** [wysiib/plspec#9]
Consider the following (spec'd) predicate:

```
:- spec_post(my_member/2, [list(X), var], [list(X), X]).
my_member([H|_], H).
```

Then, assume the query `my_member([1,2,3],X).`

Expected behaviour: the post condition is selected to be checked later on.
Actual behaviour: the unification of `H` in `my_member` happens before the `which_posts` check occurs, therefore `H` is not bound to the variable `X` but rather to the value `1`. Thus, the post condition is discarded.
Suggested fix: switch ordering of `which_posts` and the unification with the head of the clause if possible. This has to modify the term expander.

**Comment by isabelwingen** [comment]
The issues was that a precondition containing var did not fire, and because of that the post condition did not get checked. 

The suggested fix solved the Problem.
